In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch
from torch import nn
import torch.nn.functional as F
import numpy as np
from torch.utils.data import WeightedRandomSampler
from torch_geometric.nn.conv import GATConv, GCNConv, SplineConv
from torch_geometric.nn.norm import GraphNorm
from torch_geometric.nn import Sequential
from torch_geometric.data import Data, Batch
from torch_geometric.loader import DataLoader
import torch.utils.data as torchdata
import tqdm
from math import floor
import gc
import matplotlib.pyplot as plt
from Model.MENDR.MENDR import MENDR_model
from Model.MENDR.MENDREncoder import MENDRPatchEncoder
from Model.MENDR.mAtt.optimizer import MixOptimizer
from Model.MENDR.mAtt.spd import SPDTangentSpace
import random
import os
import math
from Datasets.datasetTUEV import WaveletTUEVDataset
from sklearn.metrics import accuracy_score, balanced_accuracy_score, roc_auc_score, precision_recall_curve, auc, f1_score
from torchjd import mtl_backward
from torchjd.aggregation import UPGrad

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

cuda


In [3]:
print("*" * 50)
finetune_train_dataset = WaveletTUEVDataset(root="/home/hice1/mchen439/scratch/TUEV/train", frac=1.0, split="train")
print("Dataset Loaded. Length of Train Dataset: ", len(finetune_train_dataset))
finetune_eval_dataset = WaveletTUEVDataset(root="/home/hice1/mchen439/scratch/TUEV/eval", frac=1.0, split="eval")
print("Dataset Loaded. Length of Validation Dataset: ", len(finetune_eval_dataset))

**************************************************
Loading 83932 folders


 15%|█▍        | 12284/83932 [00:33<02:59, 398.05it/s]

In [ ]:
print(finetune_eval_dataset[0]['graph'])
print(finetune_eval_dataset[0]['delta'].shape)
print(finetune_eval_dataset[0]['theta'].shape)
print(finetune_eval_dataset[0]['alpha'].shape)
print(finetune_eval_dataset[0]['beta'].shape)
print(finetune_eval_dataset[0]['gamma'].shape)
print(finetune_eval_dataset[0]['graph'].y)
print(finetune_eval_dataset[1]['graph'].y)
print(finetune_eval_dataset[2]['graph'].y)
print(finetune_eval_dataset[3]['graph'].y)
print(finetune_eval_dataset[4]['graph'].y)
print(finetune_eval_dataset[5]['graph'].y)
print(finetune_eval_dataset[6]['graph'].y)
print(finetune_eval_dataset[7]['graph'].y)
print(finetune_eval_dataset[8]['graph'].y)
print(finetune_eval_dataset[9]['graph'].y)
print(finetune_eval_dataset[29000]['graph'].y)
print(finetune_eval_dataset[29010]['graph'].y)
print(finetune_eval_dataset[29020]['graph'].y)
print(finetune_eval_dataset[29030]['graph'].y)

Data(edge_index=[2, 361], edge_attr=[361, 1], pos=[19, 3], y=[1])
torch.Size([19, 86])
torch.Size([19, 86])
torch.Size([19, 166])
torch.Size([19, 326])
torch.Size([19, 645])
tensor([5])
tensor([5])
tensor([4])
tensor([5])
tensor([1])
tensor([5])
tensor([5])
tensor([4])
tensor([0])
tensor([5])
tensor([5])
tensor([5])
tensor([1])
tensor([5])


In [ ]:
train_label_count = {
    0: 0,
    1: 0,
    2: 0,
    3: 0,
    4: 0,
    5: 0
}
y_train = []
for i in range(len(finetune_train_dataset)):
    graph = finetune_train_dataset[i]['graph']
    train_label = graph.y.item()
    assert train_label >= 0 and train_label <= 5, f"Label {train_label} is not in range [0, 5]"
    train_label_count[train_label] += 1
    y_train.append(train_label)

print(train_label_count)

{0: 645, 1: 11254, 2: 6184, 3: 1070, 4: 11053, 5: 53726}


In [ ]:
test_label_count = {
    0: 0,
    1: 0,
    2: 0,
    3: 0,
    4: 0,
    5: 0
}

y_test = []
for i in range(len(finetune_eval_dataset)):
    graph = finetune_eval_dataset[i]['graph']
    test_label = graph.y.item()
    assert test_label >= 0 and test_label <= 5, f"{test_label} is not a valid label"
    test_label_count[test_label] += 1
    y_test.append(test_label)

print(test_label_count)

{0: 567, 1: 4677, 2: 1998, 3: 329, 4: 2204, 5: 19646}


In [ ]:
train_label_counts_arr = np.array(list(train_label_count.values()))
train_sampler_class_weight = 1. / torch.from_numpy(train_label_counts_arr)
train_samples_weight = np.array([train_sampler_class_weight[t] for t in y_train])
train_sampler = WeightedRandomSampler(weights=train_samples_weight, num_samples=len(train_samples_weight))

test_label_counts_arr = np.array(list(test_label_count.values()))
test_sampler_class_weight = 1. / torch.from_numpy(test_label_counts_arr)
test_samples_weight = np.array([test_sampler_class_weight[t] for t in y_test])
test_sampler = WeightedRandomSampler(weights=test_samples_weight, num_samples=len(test_samples_weight))

print(train_sampler_class_weight)
print(test_sampler_class_weight)
print(train_samples_weight.shape)
print(test_samples_weight.shape)

tensor([1.5504e-03, 8.8857e-05, 1.6171e-04, 9.3458e-04, 9.0473e-05, 1.8613e-05])
tensor([1.7637e-03, 2.1381e-04, 5.0050e-04, 3.0395e-03, 4.5372e-04, 5.0901e-05])
(83932,)
(29421,)


In [8]:
finetune_train_loader = DataLoader(finetune_train_dataset, batch_size=256, num_workers=8, pin_memory=True, persistent_workers=True, shuffle=True)
finetune_eval_loader = DataLoader(finetune_eval_dataset, batch_size=256, num_workers=8, pin_memory=True, persistent_workers=True, shuffle=False)
print(len(finetune_train_loader), len(finetune_eval_loader))
BANDS = ['delta', 'theta', 'alpha', 'beta', 'gamma']

656 230


In [9]:
class FinetuneDecoder(nn.Module):
    def __init__(self, device):
        super().__init__()
        self.tangent = SPDTangentSpace(19, device=device)
        self.flatten = nn.Flatten()

        self.band_tangent_spaces = nn.ParameterDict({
            'delta': SPDTangentSpace(19, device=device),
            'theta': SPDTangentSpace(19, device=device),
            'alpha': SPDTangentSpace(19, device=device),
            'beta':  SPDTangentSpace(19, device=device),
            'gamma': SPDTangentSpace(19, device=device),
        })

        self.band_flatten = nn.ParameterDict({
            'delta': nn.Flatten(),
            'theta': nn.Flatten(),
            'alpha': nn.Flatten(),
            'beta':  nn.Flatten(),
            'gamma': nn.Flatten(),
        })

        self.band_dim = {
            'delta': 19,
            'theta': 19,
            'alpha': 19,
            'beta':  19,
            'gamma': 19,
        }

        self.flattened = (19 * 20) // 2

        self.band_decoders = nn.ParameterDict({
            'delta': nn.Sequential(nn.GELU(), nn.LayerNorm(self.flattened), nn.Dropout(p=0.2), nn.Linear(self.flattened, 10), nn.LayerNorm(10), nn.Dropout(p=0.1)),
            'theta': nn.Sequential(nn.GELU(), nn.LayerNorm(self.flattened), nn.Dropout(p=0.2), nn.Linear(self.flattened, 10), nn.LayerNorm(10), nn.Dropout(p=0.1)),
            'alpha': nn.Sequential(nn.GELU(), nn.LayerNorm(self.flattened), nn.Dropout(p=0.2), nn.Linear(self.flattened, 10), nn.LayerNorm(10), nn.Dropout(p=0.1)),
            'beta':  nn.Sequential(nn.GELU(), nn.LayerNorm(self.flattened), nn.Dropout(p=0.2), nn.Linear(self.flattened, 10), nn.LayerNorm(10), nn.Dropout(p=0.1)),
            'gamma': nn.Sequential(nn.GELU(), nn.LayerNorm(self.flattened), nn.Dropout(p=0.2), nn.Linear(self.flattened, 10), nn.LayerNorm(10), nn.Dropout(p=0.1)),
        })
        self.combined_seq = nn.Sequential(nn.LayerNorm(19 * 10), nn.Dropout(p=0.2), nn.Linear(19*10, 10), nn.GELU())
        self.final_decoder = nn.Linear(5*10 + 10, 6)

    def forward(self, wavelet_manifold_output, combined_manifold_output):
        batch_size = combined_manifold_output.shape[0]
        num_patches = combined_manifold_output.shape[1]
        embedding_dim = combined_manifold_output.shape[2]
        
        band_decodings = []
        for band, encodings in wavelet_manifold_output.items():
            #print(band, encodings.shape, self.band_dim[band])
            band_tangent = self.band_tangent_spaces[band](encodings.view(batch_size*num_patches, self.band_dim[band], self.band_dim[band]))
            band_tangent = self.band_flatten[band](band_tangent)
            band_decoding = self.band_decoders[band](band_tangent)
            band_decodings.append(band_decoding)
        band_decodings = torch.cat(band_decodings, dim=1)

        x = self.tangent(combined_manifold_output.view(batch_size*num_patches, embedding_dim, embedding_dim))
        #x = x.view(batch_size, num_patches, -1)
        x = self.flatten(x)
        x = self.combined_seq(x)
        return self.final_decoder(torch.cat([x, band_decodings], dim=1))

In [10]:
model = MENDR_model(device=device, contextualizer_size="LARGE").to(device)
model.load_state_dict(torch.load("./checkpoint/4b5781b2c41e45a7a666bb8c29b4ae22_14_LARGE/mendr_model_weights.pth", weights_only=True))
model_decoder = FinetuneDecoder(device).to(device)
optim_params = []
optim_params.append({'params': model.mendr_encoder.parameters(), 'lr': 1e-5})
optim_params.append({'params': model.mendr_contextualizer.parameters(), 'lr': 1e-5})
optim_params.append({'params': model_decoder.parameters(), 'lr': 1e-5})
optimizer = MixOptimizer(torch.optim.AdamW(optim_params, lr=1e-5, weight_decay=1e-4))
optimizer.set_scheduler_t0(len(finetune_train_loader) * 15)
for p in model.mendr_contextualizer.parameters():
    p.register_hook(lambda grad: torch.clamp(grad, -1e7, 1e7))
for p in model_decoder.parameters():
    p.register_hook(lambda grad: torch.clamp(grad, -1e7, 1e7))
aggregator = UPGrad(pref_vector=torch.tensor([1, 1, 1, 1, 1, 1]).to(device))
print("Total MENDR parameters:", sum(p.numel() for p in model.parameters() if p.requires_grad))
print("Total model_decoder parameters:", sum(p.numel() for p in model_decoder.parameters() if p.requires_grad))
total_encoder_params = 0
total_decoder_params = 0
for band in BANDS:
    print(f'{band} Encoder Params: {model.mendr_encoder.encoder_decoders[band].getEncoderParamCount()}')
    print(f'{band} Decoder Params: {model.mendr_encoder.encoder_decoders[band].getDecoderParamCount()}')
    total_encoder_params += model.mendr_encoder.encoder_decoders[band].getEncoderParamCount()
    total_decoder_params += model.mendr_encoder.encoder_decoders[band].getDecoderParamCount()
print(f'Wavelet Contextualizer Params: {sum(p.numel() for p in model.mendr_contextualizer.WaveletContextualizer.parameters() if p.requires_grad)}')
print(f'Combined Contextualizer Params: {sum(p.numel() for p in model.mendr_contextualizer.CombinedContextualizer.parameters() if p.requires_grad)}')
print(f'Contextualizer Params: {sum(p.numel() for p in model.mendr_contextualizer.parameters() if p.requires_grad)}')
print("Total Encoder Params: ", total_encoder_params)
print("Total Decoder Params: ", total_decoder_params)

Set Cosine Annealing with Warm Restarts optimizer T_0 to: 656
Total MENDR parameters: 2448254
Total model_decoder parameters: 14106
delta Encoder Params: 12597
delta Decoder Params: 22309
theta Encoder Params: 12597
theta Decoder Params: 22309
alpha Encoder Params: 14041
alpha Decoder Params: 101219
beta Encoder Params: 16929
beta Decoder Params: 498051
gamma Encoder Params: 22705
gamma Decoder Params: 1622675
Wavelet Contextualizer Params: 68027
Combined Contextualizer Params: 2760
Contextualizer Params: 70788
Total Encoder Params:  78869
Total Decoder Params:  2266563


In [11]:
def _fft_loss(output, target, loss_fn):
    hanning_window = torch.hann_window(output.shape[-1]).to(device)
    output_windowed = output * hanning_window.expand_as(output)
    target_windowed = target * hanning_window.expand_as(target)

    output_fft = torch.fft.fft(output_windowed, dim=-1)
    output_amplitude = torch.abs(output_fft)
    output_angle = torch.angle(output_fft)

    target_fft = torch.fft.fft(target_windowed, dim=-1)
    target_amplitude = torch.abs(target_fft)
    target_angle = torch.abs(target_fft)

    return (loss_fn(output_amplitude, target_amplitude) + (loss_fn(output_angle, target_angle)))

def calculate_band_loss(inputs, outputs, loss_fn, loss_type='real'):
    outputs_reshaped = outputs.reshape(inputs.shape[0], inputs.shape[1], inputs.shape[2], inputs.shape[3])
    if loss_type == 'real':
        loss = loss_fn(inputs, outputs_reshaped)
    elif loss_type == 'fourier':
        loss = _fft_loss(output_reshaped, inputs, loss_fn)
    else:
        loss = loss_fn(inputs, outputs_reshaped) + _fft_loss(output_reshaped, inputs, loss_fn) * 1e-2
    return loss

In [12]:
def train_one_epoch(model, epoch, decoder, optimizer, task_loss_fn, recon_loss_fn, train_loader):
	task_loss_sum = 0
	recon_loss_sum = 0
	model.eval()
	decoder.train()

	pbar = tqdm.trange(len(train_loader), desc="Training")
	data_iterator = iter(train_loader)
	balanced_accuracies = []

	truths = []
	preds = []
	for iteration in pbar:
		data = next(data_iterator)
		relevant_bands = [data['delta'].float().to(device),
							data['theta'].float().to(device),
							data['alpha'].float().to(device),
							data['beta'].float().to(device),
							data['gamma'].float().to(device)]
		inputs = dict(zip(BANDS, relevant_bands))
		patchified_inputs, encodings, decodings, wavelet_manifold_output, combined_manifold_output = model(data['graph'], inputs)
		wavelet_manifold_output_relevant_patch = dict()
		for band, wavelet_manifold in wavelet_manifold_output.items():
			wavelet_manifold_output_relevant_patch[band] = wavelet_manifold[:, 1, :, :][:, None, :, :]
		prediction = decoder(wavelet_manifold_output_relevant_patch, combined_manifold_output[:, 1, :, :][:, None, :, :]).float()
		ground_truth = data['graph'].y.to(device).long()
		task_loss = task_loss_fn(prediction, ground_truth)
		delta_loss = calculate_band_loss(patchified_inputs['delta'], decodings['delta'], recon_loss_fn)
		theta_loss = calculate_band_loss(patchified_inputs['theta'], decodings['theta'], recon_loss_fn)
		alpha_loss = calculate_band_loss(patchified_inputs['alpha'], decodings['alpha'], recon_loss_fn)
		beta_loss = calculate_band_loss(patchified_inputs['beta'],   decodings['beta'], recon_loss_fn)
		gamma_loss = calculate_band_loss(patchified_inputs['gamma'], decodings['gamma'], recon_loss_fn)
		# Borrowed from CBramod: https://github.com/wjq-learning/CBraMod/blob/e0002aaa87e77a954ce3a11cb1de1ea13e3585e2/finetune_evaluator.py
		with torch.no_grad():
			pred_y = torch.max(prediction, dim=-1)[1]
			truths += ground_truth.clone().cpu().squeeze().numpy().tolist()
			preds += pred_y.clone().cpu().squeeze().numpy().tolist()
			curr_balanced_accuracy = balanced_accuracy_score(ground_truth.clone().cpu().squeeze().numpy(), pred_y.clone().cpu().squeeze().numpy())
			curr_f1 = f1_score(ground_truth.clone().cpu().squeeze().numpy(), pred_y.clone().cpu().squeeze().numpy(), average='weighted')


		shared_features = [encoding for band, encoding in encodings.items()]
		optimizer.zero_grad()
		#task_loss.backward()
		mtl_backward(losses=[task_loss, delta_loss, theta_loss, alpha_loss, beta_loss, gamma_loss], features=shared_features, aggregator=aggregator)
		optimizer.step()
		optimizer.scheduler_step(epoch * len(train_loader) + iteration)
		task_loss_sum += task_loss.item()
		recon_loss = delta_loss.item() + theta_loss.item() + alpha_loss.item() + beta_loss.item() + gamma_loss.item()
		recon_loss_sum += recon_loss
		pbar.set_postfix(task_loss=task_loss.item(), recon_loss=recon_loss, balanced_accuracy=f'{curr_balanced_accuracy*100:.3f}', F1=f'{curr_f1*100:.3f}', lr=optimizer.scheduler.get_last_lr()[0])

	truths = np.array(truths)
	preds = np.array(preds)

	balanced_accuracy = balanced_accuracy_score(truths, preds)
	f1 = f1_score(truths, preds, average='weighted')
	print(f'Mean Acc: {balanced_accuracy} F1 Score: {f1}')
	return task_loss_sum, recon_loss_sum

In [13]:
def validate_one_epoch(model, decoder, task_loss_fn, recon_loss_fn, val_loader):
	task_loss_sum = 0
	recon_loss_sum = 0
	model.eval()
	decoder.eval()

	pbar = tqdm.trange(len(val_loader), desc="Validating")
	data_iterator = iter(val_loader)
	balanced_accuracies = []
	auc_pr = []
	auroc = []

	truths = []
	preds = []
	with torch.no_grad():
		for iteration in pbar:
			data = next(data_iterator)
			relevant_bands = [data['delta'].float().to(device),
								data['theta'].float().to(device),
								data['alpha'].float().to(device),
								data['beta'].float().to(device),
								data['gamma'].float().to(device)]
			inputs = dict(zip(BANDS, relevant_bands))
			encoder_outputs = model(data['graph'], inputs)
			patchified_inputs, encodings, decodings, wavelet_manifold_output, combined_manifold_output = model(data['graph'], inputs)
			wavelet_manifold_output_relevant_patch = dict()
			for band, wavelet_manifold in wavelet_manifold_output.items():
				wavelet_manifold_output_relevant_patch[band] = wavelet_manifold[:, 1, :, :][:, None, :, :]
			prediction = decoder(wavelet_manifold_output_relevant_patch, combined_manifold_output[:, 1, :, :][:, None, :, :]).float()
			ground_truth = data['graph'].y.to(device).long()

			task_loss = task_loss_fn(prediction, ground_truth)

			delta_loss = calculate_band_loss(patchified_inputs['delta'], decodings['delta'], recon_loss_fn)
			theta_loss = calculate_band_loss(patchified_inputs['theta'], decodings['theta'], recon_loss_fn)
			alpha_loss = calculate_band_loss(patchified_inputs['alpha'], decodings['alpha'], recon_loss_fn)
			beta_loss = calculate_band_loss(patchified_inputs['beta'],   decodings['beta'], recon_loss_fn)
			gamma_loss = calculate_band_loss(patchified_inputs['gamma'], decodings['gamma'], recon_loss_fn)

			pred_y = torch.max(prediction, dim=-1)[1]
			truths += ground_truth.clone().cpu().squeeze().numpy().tolist()
			preds += pred_y.clone().cpu().squeeze().numpy().tolist()

			task_loss_sum += task_loss.item()
			recon_loss = delta_loss.item() + theta_loss.item() + alpha_loss.item() + beta_loss.item() + gamma_loss.item()
			recon_loss_sum += recon_loss

			curr_balanced_accuracy = balanced_accuracy_score(ground_truth.clone().cpu().squeeze().numpy(), pred_y.clone().cpu().squeeze().numpy())
			curr_f1 = f1_score(ground_truth.clone().cpu().squeeze().numpy(), pred_y.clone().cpu().squeeze().numpy(), average='weighted')

			pbar.set_postfix(task_loss=task_loss.item(), recon_loss=recon_loss, balanced_accuracy=f'{curr_balanced_accuracy*100:.3f}', F1=f'{curr_f1*100:.3f}', lr=optimizer.scheduler.get_last_lr()[0])
		truths = np.array(truths)
		preds = np.array(preds)

		balanced_accuracy = balanced_accuracy_score(truths, preds)
		f1 = f1_score(truths, preds, average='weighted')

		print(f'Mean Acc: {balanced_accuracy} F1 Score: {f1}')
	return task_loss_sum, recon_loss_sum, balanced_accuracy, f1

In [14]:
import warnings
warnings.filterwarnings('ignore', category=UserWarning)

In [15]:
BANDS = ['delta', 'theta', 'alpha', 'beta', 'gamma']
for epoch_idx in range(15):
    training_task_loss, training_recon_loss = train_one_epoch(model, epoch_idx, model_decoder, optimizer, nn.CrossEntropyLoss(label_smoothing=0.1), nn.MSELoss(), finetune_train_loader)
    eval_task_loss, eval_recon_loss, balanced_accuracy, f1 = validate_one_epoch(model, model_decoder, nn.CrossEntropyLoss(label_smoothing=0.1), nn.MSELoss(), finetune_eval_loader)
    print("*" * 50)
    print(f"Epoch: {epoch_idx}")
    print("Epoch: ", epoch_idx, "Total Training Task Loss: ", training_task_loss, "Total Training Recon Loss:", training_recon_loss, "Total Validation Task Loss: ", eval_task_loss, "Total Validation Recon Loss:", eval_recon_loss)
    print("Epoch: ", epoch_idx, "Total Validation Task Loss: ", eval_task_loss, "Total Validation Recon Loss:", eval_recon_loss)
    print("Epoch: ", epoch_idx, "Eval Acc", balanced_accuracy, "F1", f1)

Training: 100%|██████████| 656/656 [03:15<00:00,  3.36it/s, F1=89.728, balanced_accuracy=58.468, lr=1.01e-7, recon_loss=3.64e+4, task_loss=0.668]


Mean Acc: 0.543175993514563 F1 Score: 0.8585926476776788


Validating: 100%|██████████| 230/230 [01:02<00:00,  3.65it/s, F1=68.694, balanced_accuracy=32.184, lr=1.01e-7, recon_loss=7.34e+3, task_loss=1.02] 


Mean Acc: 0.35104617323106285 F1 Score: 0.6960270231737216
**************************************************
Epoch: 0
Epoch:  0 Total Training Task Loss:  490.39687728881836 Total Training Recon Loss: 7059881.337889016 Total Validation Task Loss:  235.436893761158 Total Validation Recon Loss: 3246380.7359154224
Epoch:  0 Total Validation Task Loss:  235.436893761158 Total Validation Recon Loss: 3246380.7359154224
Epoch:  0 Eval Acc 0.35104617323106285 F1 0.6960270231737216


Training: 100%|██████████| 656/656 [03:11<00:00,  3.42it/s, F1=93.546, balanced_accuracy=76.842, lr=5.02e-5, recon_loss=4.4e+3, task_loss=0.581] 


Mean Acc: 0.6476838796628457 F1 Score: 0.9259948755114326


Validating: 100%|██████████| 230/230 [00:59<00:00,  3.83it/s, F1=71.732, balanced_accuracy=38.302, lr=5.02e-5, recon_loss=7.36e+3, task_loss=1.05] 


Mean Acc: 0.441032503986677 F1 Score: 0.7227864910940509
**************************************************
Epoch: 1
Epoch:  1 Total Training Task Loss:  403.0172030925751 Total Training Recon Loss: 7044130.526955903 Total Validation Task Loss:  238.17752408981323 Total Validation Recon Loss: 3253979.2109906673
Epoch:  1 Total Validation Task Loss:  238.17752408981323 Total Validation Recon Loss: 3253979.2109906673
Epoch:  1 Eval Acc 0.441032503986677 F1 0.7227864910940509


Training: 100%|██████████| 656/656 [03:13<00:00,  3.38it/s, F1=94.585, balanced_accuracy=77.647, lr=1e-7, recon_loss=6.2e+4, task_loss=0.556]     


Mean Acc: 0.7140568220673703 F1 Score: 0.9507587876587223


Validating: 100%|██████████| 230/230 [01:00<00:00,  3.83it/s, F1=72.055, balanced_accuracy=37.404, lr=1e-7, recon_loss=7.37e+3, task_loss=1.03] 


Mean Acc: 0.41705672059610316 F1 Score: 0.7233464688401308
**************************************************
Epoch: 2
Epoch:  2 Total Training Task Loss:  364.1388681232929 Total Training Recon Loss: 7047441.103257358 Total Validation Task Loss:  238.7716765999794 Total Validation Recon Loss: 3254183.7943167686
Epoch:  2 Total Validation Task Loss:  238.7716765999794 Total Validation Recon Loss: 3254183.7943167686
Epoch:  2 Eval Acc 0.41705672059610316 F1 0.7233464688401308


Training: 100%|██████████| 656/656 [03:12<00:00,  3.40it/s, F1=96.664, balanced_accuracy=93.143, lr=8.54e-5, recon_loss=3.15e+4, task_loss=0.543] 


Mean Acc: 0.7342097255739283 F1 Score: 0.9550815276535113


Validating: 100%|██████████| 230/230 [01:00<00:00,  3.82it/s, F1=73.947, balanced_accuracy=41.777, lr=8.54e-5, recon_loss=7.37e+3, task_loss=1.03] 


Mean Acc: 0.4272599847104777 F1 Score: 0.707476884812112
**************************************************
Epoch: 3
Epoch:  3 Total Training Task Loss:  360.89420342445374 Total Training Recon Loss: 7023557.787972093 Total Validation Task Loss:  239.60186731815338 Total Validation Recon Loss: 3248432.2017149925
Epoch:  3 Total Validation Task Loss:  239.60186731815338 Total Validation Recon Loss: 3248432.2017149925
Epoch:  3 Eval Acc 0.4272599847104777 F1 0.707476884812112


Training: 100%|██████████| 656/656 [03:14<00:00,  3.37it/s, F1=100.000, balanced_accuracy=100.000, lr=5.01e-5, recon_loss=887, task_loss=0.464]    


Mean Acc: 0.7859981465913123 F1 Score: 0.9664211707960403


Validating: 100%|██████████| 230/230 [01:00<00:00,  3.83it/s, F1=76.016, balanced_accuracy=44.222, lr=5.01e-5, recon_loss=7.37e+3, task_loss=1.02] 


Mean Acc: 0.4311985043425075 F1 Score: 0.7272762267431941
**************************************************
Epoch: 4
Epoch:  4 Total Training Task Loss:  341.94256806373596 Total Training Recon Loss: 6986270.003378332 Total Validation Task Loss:  237.741565823555 Total Validation Recon Loss: 3245049.736131668
Epoch:  4 Total Validation Task Loss:  237.741565823555 Total Validation Recon Loss: 3245049.736131668
Epoch:  4 Eval Acc 0.4311985043425075 F1 0.7272762267431941


Training: 100%|██████████| 656/656 [03:12<00:00,  3.40it/s, F1=100.000, balanced_accuracy=100.000, lr=1.48e-5, recon_loss=5.81e+3, task_loss=0.461]


Mean Acc: 0.821023390559822 F1 Score: 0.9726611621968116


Validating: 100%|██████████| 230/230 [01:00<00:00,  3.80it/s, F1=74.092, balanced_accuracy=41.635, lr=1.48e-5, recon_loss=7.37e+3, task_loss=1.02] 


Mean Acc: 0.44678034591494625 F1 Score: 0.7172785493981175
**************************************************
Epoch: 5
Epoch:  5 Total Training Task Loss:  332.17173594236374 Total Training Recon Loss: 6968008.741737902 Total Validation Task Loss:  243.30188584327698 Total Validation Recon Loss: 3243487.091814995
Epoch:  5 Total Validation Task Loss:  243.30188584327698 Total Validation Recon Loss: 3243487.091814995
Epoch:  5 Eval Acc 0.44678034591494625 F1 0.7172785493981175


Training: 100%|██████████| 656/656 [03:10<00:00,  3.45it/s, F1=97.198, balanced_accuracy=94.621, lr=1e-7, recon_loss=1.87e+4, task_loss=0.496]     


Mean Acc: 0.8352155296104581 F1 Score: 0.9750340565051296


Validating: 100%|██████████| 230/230 [01:00<00:00,  3.78it/s, F1=75.114, balanced_accuracy=42.148, lr=1e-7, recon_loss=7.37e+3, task_loss=1.02] 


Mean Acc: 0.441321312018071 F1 Score: 0.7197648320963926
**************************************************
Epoch: 6
Epoch:  6 Total Training Task Loss:  327.7561832666397 Total Training Recon Loss: 6966639.069395721 Total Validation Task Loss:  241.50842362642288 Total Validation Recon Loss: 3243645.0895512104
Epoch:  6 Total Validation Task Loss:  241.50842362642288 Total Validation Recon Loss: 3243645.0895512104
Epoch:  6 Eval Acc 0.441321312018071 F1 0.7197648320963926


Training: 100%|██████████| 656/656 [03:12<00:00,  3.41it/s, F1=92.970, balanced_accuracy=79.167, lr=9.62e-5, recon_loss=588, task_loss=0.551]      


Mean Acc: 0.8176268462694489 F1 Score: 0.9719726810316376


Validating: 100%|██████████| 230/230 [01:00<00:00,  3.82it/s, F1=75.187, balanced_accuracy=42.404, lr=9.62e-5, recon_loss=7.38e+3, task_loss=1.05] 


Mean Acc: 0.4450310050535638 F1 Score: 0.7230271947377084
**************************************************
Epoch: 7
Epoch:  7 Total Training Task Loss:  336.24744468927383 Total Training Recon Loss: 6954683.928130388 Total Validation Task Loss:  247.56028932332993 Total Validation Recon Loss: 3241897.2046768665
Epoch:  7 Total Validation Task Loss:  247.56028932332993 Total Validation Recon Loss: 3241897.2046768665
Epoch:  7 Eval Acc 0.4450310050535638 F1 0.7230271947377084


Training: 100%|██████████| 656/656 [03:12<00:00,  3.42it/s, F1=93.470, balanced_accuracy=80.000, lr=8.54e-5, recon_loss=742, task_loss=0.567]      


Mean Acc: 0.8527002092705166 F1 Score: 0.9770699129104489


Validating: 100%|██████████| 230/230 [01:00<00:00,  3.83it/s, F1=75.752, balanced_accuracy=64.910, lr=8.54e-5, recon_loss=7.41e+3, task_loss=1.05] 


Mean Acc: 0.45840532438304255 F1 Score: 0.7131435678208925
**************************************************
Epoch: 8
Epoch:  8 Total Training Task Loss:  327.6759729087353 Total Training Recon Loss: 6931986.800906897 Total Validation Task Loss:  250.49495023488998 Total Validation Recon Loss: 3243984.3531644344
Epoch:  8 Total Validation Task Loss:  250.49495023488998 Total Validation Recon Loss: 3243984.3531644344
Epoch:  8 Eval Acc 0.45840532438304255 F1 0.7131435678208925


Training: 100%|██████████| 656/656 [03:09<00:00,  3.46it/s, F1=97.830, balanced_accuracy=97.778, lr=6.92e-5, recon_loss=368, task_loss=0.488]      


Mean Acc: 0.8792670886228713 F1 Score: 0.9805712820785287


Validating: 100%|██████████| 230/230 [01:00<00:00,  3.81it/s, F1=75.681, balanced_accuracy=44.282, lr=6.92e-5, recon_loss=7.41e+3, task_loss=1.05] 


Mean Acc: 0.44962418316370156 F1 Score: 0.7066184317586114
**************************************************
Epoch: 9
Epoch:  9 Total Training Task Loss:  322.16209402680397 Total Training Recon Loss: 6912561.355177522 Total Validation Task Loss:  255.82352685928345 Total Validation Recon Loss: 3238085.24273026
Epoch:  9 Total Validation Task Loss:  255.82352685928345 Total Validation Recon Loss: 3238085.24273026
Epoch:  9 Eval Acc 0.44962418316370156 F1 0.7066184317586114


Training: 100%|██████████| 656/656 [03:10<00:00,  3.44it/s, F1=98.887, balanced_accuracy=96.667, lr=5.01e-5, recon_loss=5.6e+3, task_loss=0.472]   


Mean Acc: 0.8859504576345909 F1 Score: 0.9816060226793576


Validating: 100%|██████████| 230/230 [01:00<00:00,  3.81it/s, F1=79.972, balanced_accuracy=49.049, lr=5.01e-5, recon_loss=7.42e+3, task_loss=0.992]


Mean Acc: 0.4831832461463046 F1 Score: 0.7296490062619757
**************************************************
Epoch: 10
Epoch:  10 Total Training Task Loss:  318.41528832912445 Total Training Recon Loss: 6890135.075265229 Total Validation Task Loss:  243.9373117685318 Total Validation Recon Loss: 3236463.3135330677
Epoch:  10 Total Validation Task Loss:  243.9373117685318 Total Validation Recon Loss: 3236463.3135330677
Epoch:  10 Eval Acc 0.4831832461463046 F1 0.7296490062619757


Training: 100%|██████████| 656/656 [03:10<00:00,  3.45it/s, F1=97.273, balanced_accuracy=78.000, lr=3.1e-5, recon_loss=5.72e+4, task_loss=0.511]   


Mean Acc: 0.9020030812038403 F1 Score: 0.9836352395386352


Validating: 100%|██████████| 230/230 [00:59<00:00,  3.84it/s, F1=76.608, balanced_accuracy=66.310, lr=3.1e-5, recon_loss=7.42e+3, task_loss=0.997]


Mean Acc: 0.4913487021421285 F1 Score: 0.7402701665436999
**************************************************
Epoch: 11
Epoch:  11 Total Training Task Loss:  314.95826721191406 Total Training Recon Loss: 6888485.1006371975 Total Validation Task Loss:  236.29587376117706 Total Validation Recon Loss: 3235141.577864647
Epoch:  11 Total Validation Task Loss:  236.29587376117706 Total Validation Recon Loss: 3235141.577864647
Epoch:  11 Eval Acc 0.4913487021421285 F1 0.7402701665436999


Training: 100%|██████████| 656/656 [03:45<00:00,  2.91it/s, F1=98.736, balanced_accuracy=91.667, lr=1.48e-5, recon_loss=1.93e+4, task_loss=0.472]  


Mean Acc: 0.9058447597805822 F1 Score: 0.9841117424558496


Validating: 100%|██████████| 230/230 [01:00<00:00,  3.80it/s, F1=78.939, balanced_accuracy=67.080, lr=1.48e-5, recon_loss=7.43e+3, task_loss=0.993]


Mean Acc: 0.4623122148248988 F1 Score: 0.729345086485159
**************************************************
Epoch: 12
Epoch:  12 Total Training Task Loss:  312.57337987422943 Total Training Recon Loss: 6865851.449869275 Total Validation Task Loss:  239.79875701665878 Total Validation Recon Loss: 3234891.4357836246
Epoch:  12 Total Validation Task Loss:  239.79875701665878 Total Validation Recon Loss: 3234891.4357836246
Epoch:  12 Eval Acc 0.4623122148248988 F1 0.729345086485159


Training: 100%|██████████| 656/656 [03:08<00:00,  3.48it/s, F1=100.000, balanced_accuracy=100.000, lr=3.91e-6, recon_loss=1.76e+4, task_loss=0.448]


Mean Acc: 0.91768529431199 F1 Score: 0.9853603800706981


Validating: 100%|██████████| 230/230 [01:00<00:00,  3.77it/s, F1=77.582, balanced_accuracy=66.567, lr=3.91e-6, recon_loss=7.44e+3, task_loss=0.993]


Mean Acc: 0.47770481705226525 F1 Score: 0.7317433045381936
**************************************************
Epoch: 13
Epoch:  13 Total Training Task Loss:  310.4852047264576 Total Training Recon Loss: 6860390.543334782 Total Validation Task Loss:  237.26848447322845 Total Validation Recon Loss: 3235574.996876478
Epoch:  13 Total Validation Task Loss:  237.26848447322845 Total Validation Recon Loss: 3235574.996876478
Epoch:  13 Eval Acc 0.47770481705226525 F1 0.7317433045381936


Training: 100%|██████████| 656/656 [03:23<00:00,  3.23it/s, F1=98.922, balanced_accuracy=98.684, lr=1e-7, recon_loss=5.41e+4, task_loss=0.467]     


Mean Acc: 0.9175385040612131 F1 Score: 0.9853389909915059


Validating: 100%|██████████| 230/230 [01:00<00:00,  3.79it/s, F1=77.051, balanced_accuracy=66.310, lr=1e-7, recon_loss=7.44e+3, task_loss=0.997]


Mean Acc: 0.4766441390566774 F1 Score: 0.7319921308639018
**************************************************
Epoch: 14
Epoch:  14 Total Training Task Loss:  309.80483078956604 Total Training Recon Loss: 6868625.9727525115 Total Validation Task Loss:  238.91920799016953 Total Validation Recon Loss: 3235418.2392640114
Epoch:  14 Total Validation Task Loss:  238.91920799016953 Total Validation Recon Loss: 3235418.2392640114
Epoch:  14 Eval Acc 0.4766441390566774 F1 0.7319921308639018


Training: 100%|██████████| 656/656 [03:09<00:00,  3.46it/s, F1=97.851, balanced_accuracy=95.966, lr=9.9e-5, recon_loss=2.84e+4, task_loss=0.475]   


Mean Acc: 0.8921805088249787 F1 Score: 0.9819782142772987


Validating: 100%|██████████| 230/230 [01:00<00:00,  3.79it/s, F1=77.120, balanced_accuracy=43.944, lr=9.9e-5, recon_loss=7.47e+3, task_loss=1.06] 


Mean Acc: 0.4270704757742856 F1 Score: 0.7198106930636543
**************************************************
Epoch: 15
Epoch:  15 Total Training Task Loss:  320.51633337140083 Total Training Recon Loss: 6852320.948778212 Total Validation Task Loss:  252.65414959192276 Total Validation Recon Loss: 3234126.283331156
Epoch:  15 Total Validation Task Loss:  252.65414959192276 Total Validation Recon Loss: 3234126.283331156
Epoch:  15 Eval Acc 0.4270704757742856 F1 0.7198106930636543


Training: 100%|██████████| 656/656 [03:11<00:00,  3.43it/s, F1=98.749, balanced_accuracy=91.667, lr=9.62e-5, recon_loss=2.06e+4, task_loss=0.465]  


Mean Acc: 0.903753028668592 F1 Score: 0.9832400990196106


Validating: 100%|██████████| 230/230 [01:00<00:00,  3.81it/s, F1=74.522, balanced_accuracy=42.148, lr=9.62e-5, recon_loss=7.51e+3, task_loss=1]    


Mean Acc: 0.4846270602844041 F1 Score: 0.7456935336028527
**************************************************
Epoch: 16
Epoch:  16 Total Training Task Loss:  316.3926980495453 Total Training Recon Loss: 6824255.052190185 Total Validation Task Loss:  226.79375672340393 Total Validation Recon Loss: 3234272.025181532
Epoch:  16 Total Validation Task Loss:  226.79375672340393 Total Validation Recon Loss: 3234272.025181532
Epoch:  16 Eval Acc 0.4846270602844041 F1 0.7456935336028527


Training: 100%|██████████| 656/656 [03:08<00:00,  3.47it/s, F1=100.000, balanced_accuracy=100.000, lr=9.16e-5, recon_loss=662, task_loss=0.455]    


Mean Acc: 0.9197104098199708 F1 Score: 0.9851272387524126


Validating: 100%|██████████| 230/230 [01:00<00:00,  3.82it/s, F1=76.994, balanced_accuracy=65.015, lr=9.16e-5, recon_loss=7.55e+3, task_loss=1.05] 


Mean Acc: 0.5135431226483319 F1 Score: 0.7387477882464301
**************************************************
Epoch: 17
Epoch:  17 Total Training Task Loss:  313.90309223532677 Total Training Recon Loss: 6796389.050532877 Total Validation Task Loss:  244.42259013652802 Total Validation Recon Loss: 3240814.6807062626
Epoch:  17 Total Validation Task Loss:  244.42259013652802 Total Validation Recon Loss: 3240814.6807062626
Epoch:  17 Eval Acc 0.5135431226483319 F1 0.7387477882464301


Training: 100%|██████████| 656/656 [03:08<00:00,  3.47it/s, F1=98.898, balanced_accuracy=98.571, lr=8.54e-5, recon_loss=2.09e+3, task_loss=0.455]  


Mean Acc: 0.9260243699146958 F1 Score: 0.9855774297950786


Validating: 100%|██████████| 230/230 [01:00<00:00,  3.82it/s, F1=78.209, balanced_accuracy=47.080, lr=8.54e-5, recon_loss=7.6e+3, task_loss=0.958] 


Mean Acc: 0.4488100977339875 F1 Score: 0.739498803913276
**************************************************
Epoch: 18
Epoch:  18 Total Training Task Loss:  311.6070853769779 Total Training Recon Loss: 6772833.714094818 Total Validation Task Loss:  228.8895874619484 Total Validation Recon Loss: 3241933.4748755693
Epoch:  18 Total Validation Task Loss:  228.8895874619484 Total Validation Recon Loss: 3241933.4748755693
Epoch:  18 Eval Acc 0.4488100977339875 F1 0.739498803913276


Training: 100%|██████████| 656/656 [03:12<00:00,  3.41it/s, F1=100.000, balanced_accuracy=100.000, lr=7.78e-5, recon_loss=3.24e+3, task_loss=0.458]


Mean Acc: 0.9310128269730266 F1 Score: 0.9862711948604087


Validating: 100%|██████████| 230/230 [01:00<00:00,  3.81it/s, F1=75.893, balanced_accuracy=43.966, lr=7.78e-5, recon_loss=7.63e+3, task_loss=0.982]


Mean Acc: 0.4668729249884748 F1 Score: 0.7382218644130779
**************************************************
Epoch: 19
Epoch:  19 Total Training Task Loss:  309.93564704060555 Total Training Recon Loss: 6755520.109122694 Total Validation Task Loss:  230.99548244476318 Total Validation Recon Loss: 3239889.7785897255
Epoch:  19 Total Validation Task Loss:  230.99548244476318 Total Validation Recon Loss: 3239889.7785897255
Epoch:  19 Eval Acc 0.4668729249884748 F1 0.7382218644130779


Training: 100%|██████████| 656/656 [03:07<00:00,  3.49it/s, F1=95.287, balanced_accuracy=80.702, lr=6.92e-5, recon_loss=1.89e+4, task_loss=0.508]  


Mean Acc: 0.940234515288382 F1 Score: 0.9866915374944901


Validating: 100%|██████████| 230/230 [01:00<00:00,  3.81it/s, F1=76.359, balanced_accuracy=44.900, lr=6.92e-5, recon_loss=7.68e+3, task_loss=0.984]


Mean Acc: 0.46624967057125516 F1 Score: 0.7282712147366271
**************************************************
Epoch: 20
Epoch:  20 Total Training Task Loss:  308.6011625826359 Total Training Recon Loss: 6738078.268576086 Total Validation Task Loss:  238.54126304388046 Total Validation Recon Loss: 3248538.968365431
Epoch:  20 Total Validation Task Loss:  238.54126304388046 Total Validation Recon Loss: 3248538.968365431
Epoch:  20 Eval Acc 0.46624967057125516 F1 0.7282712147366271


Training: 100%|██████████| 656/656 [03:10<00:00,  3.44it/s, F1=98.756, balanced_accuracy=90.000, lr=5.98e-5, recon_loss=1.79e+4, task_loss=0.466]  


Mean Acc: 0.9418145972192646 F1 Score: 0.9874098829464252


Validating: 100%|██████████| 230/230 [01:00<00:00,  3.81it/s, F1=75.025, balanced_accuracy=62.940, lr=5.98e-5, recon_loss=7.73e+3, task_loss=1.03] 


Mean Acc: 0.505130735162163 F1 Score: 0.744656609867624
**************************************************
Epoch: 21
Epoch:  21 Total Training Task Loss:  306.83108228445053 Total Training Recon Loss: 6712996.776077747 Total Validation Task Loss:  238.41683942079544 Total Validation Recon Loss: 3251369.338472724
Epoch:  21 Total Validation Task Loss:  238.41683942079544 Total Validation Recon Loss: 3251369.338472724
Epoch:  21 Eval Acc 0.505130735162163 F1 0.744656609867624


Training: 100%|██████████| 656/656 [03:09<00:00,  3.46it/s, F1=98.905, balanced_accuracy=98.485, lr=5.01e-5, recon_loss=1.76e+4, task_loss=0.481]  


Mean Acc: 0.9454735059588256 F1 Score: 0.9880688085925947


Validating: 100%|██████████| 230/230 [01:00<00:00,  3.82it/s, F1=75.836, balanced_accuracy=64.492, lr=5.01e-5, recon_loss=7.74e+3, task_loss=0.995]


Mean Acc: 0.4980185266592694 F1 Score: 0.7417485629450564
**************************************************
Epoch: 22
Epoch:  22 Total Training Task Loss:  305.5148171186447 Total Training Recon Loss: 6698184.835472643 Total Validation Task Loss:  234.4275186061859 Total Validation Recon Loss: 3251703.35559988
Epoch:  22 Total Validation Task Loss:  234.4275186061859 Total Validation Recon Loss: 3251703.35559988
Epoch:  22 Eval Acc 0.4980185266592694 F1 0.7417485629450564


Training: 100%|██████████| 656/656 [03:10<00:00,  3.43it/s, F1=98.885, balanced_accuracy=98.148, lr=4.03e-5, recon_loss=2.53e+4, task_loss=0.472]  


Mean Acc: 0.9486300159401909 F1 Score: 0.9882079324687679


Validating: 100%|██████████| 230/230 [01:00<00:00,  3.78it/s, F1=76.196, balanced_accuracy=63.453, lr=4.03e-5, recon_loss=7.75e+3, task_loss=0.995]


Mean Acc: 0.4787858175882465 F1 Score: 0.7379634732155705
**************************************************
Epoch: 23
Epoch:  23 Total Training Task Loss:  304.2493100762367 Total Training Recon Loss: 6684678.07330507 Total Validation Task Loss:  233.83375924825668 Total Validation Recon Loss: 3247937.5809500217
Epoch:  23 Total Validation Task Loss:  233.83375924825668 Total Validation Recon Loss: 3247937.5809500217
Epoch:  23 Eval Acc 0.4787858175882465 F1 0.7379634732155705


Training: 100%|██████████| 656/656 [03:08<00:00,  3.47it/s, F1=98.393, balanced_accuracy=80.000, lr=3.09e-5, recon_loss=405, task_loss=0.456]      


Mean Acc: 0.9523974459839452 F1 Score: 0.9887794610406652


Validating: 100%|██████████| 230/230 [01:00<00:00,  3.79it/s, F1=75.052, balanced_accuracy=64.131, lr=3.09e-5, recon_loss=7.77e+3, task_loss=1]    


Mean Acc: 0.489031568227752 F1 Score: 0.7388170044578036
**************************************************
Epoch: 24
Epoch:  24 Total Training Task Loss:  303.2907956838608 Total Training Recon Loss: 6660447.087270081 Total Validation Task Loss:  232.12613892555237 Total Validation Recon Loss: 3251535.9615689516
Epoch:  24 Total Validation Task Loss:  232.12613892555237 Total Validation Recon Loss: 3251535.9615689516
Epoch:  24 Eval Acc 0.489031568227752 F1 0.7388170044578036


Training: 100%|██████████| 656/656 [03:11<00:00,  3.42it/s, F1=100.000, balanced_accuracy=100.000, lr=2.23e-5, recon_loss=363, task_loss=0.444]    


Mean Acc: 0.9532469859945726 F1 Score: 0.9889619368016849


Validating: 100%|██████████| 230/230 [01:00<00:00,  3.82it/s, F1=75.940, balanced_accuracy=65.798, lr=2.23e-5, recon_loss=7.8e+3, task_loss=1.01]  


Mean Acc: 0.4988819583893837 F1 Score: 0.7352584320429261
**************************************************
Epoch: 25
Epoch:  25 Total Training Task Loss:  302.16489028930664 Total Training Recon Loss: 6655011.331643462 Total Validation Task Loss:  236.31553798913956 Total Validation Recon Loss: 3254670.1244938374
Epoch:  25 Total Validation Task Loss:  236.31553798913956 Total Validation Recon Loss: 3254670.1244938374
Epoch:  25 Eval Acc 0.4988819583893837 F1 0.7352584320429261


Training: 100%|██████████| 656/656 [03:11<00:00,  3.43it/s, F1=97.754, balanced_accuracy=94.286, lr=1.47e-5, recon_loss=362, task_loss=0.47]       


Mean Acc: 0.9565753454742577 F1 Score: 0.9891979309141838


Validating: 100%|██████████| 230/230 [00:59<00:00,  3.83it/s, F1=75.677, balanced_accuracy=64.387, lr=1.47e-5, recon_loss=7.8e+3, task_loss=1]     


Mean Acc: 0.48453458261427246 F1 Score: 0.728917363745698
**************************************************
Epoch: 26
Epoch:  26 Total Training Task Loss:  301.32332414388657 Total Training Recon Loss: 6651290.589212358 Total Validation Task Loss:  238.16849499940872 Total Validation Recon Loss: 3251839.415789604
Epoch:  26 Total Validation Task Loss:  238.16849499940872 Total Validation Recon Loss: 3251839.415789604
Epoch:  26 Eval Acc 0.48453458261427246 F1 0.728917363745698


Training: 100%|██████████| 656/656 [03:12<00:00,  3.41it/s, F1=100.000, balanced_accuracy=100.000, lr=8.53e-6, recon_loss=1.8e+4, task_loss=0.441] 


Mean Acc: 0.9577290275965441 F1 Score: 0.9894493599415466


Validating: 100%|██████████| 230/230 [01:00<00:00,  3.78it/s, F1=75.882, balanced_accuracy=65.949, lr=8.53e-6, recon_loss=7.81e+3, task_loss=1.01] 


Mean Acc: 0.4897464777369887 F1 Score: 0.7295584706778868
**************************************************
Epoch: 27
Epoch:  27 Total Training Task Loss:  300.69279316067696 Total Training Recon Loss: 6648721.70703423 Total Validation Task Loss:  238.68899822235107 Total Validation Recon Loss: 3253635.8755913973
Epoch:  27 Total Validation Task Loss:  238.68899822235107 Total Validation Recon Loss: 3253635.8755913973
Epoch:  27 Eval Acc 0.4897464777369887 F1 0.7295584706778868


Training: 100%|██████████| 656/656 [03:14<00:00,  3.38it/s, F1=100.000, balanced_accuracy=100.000, lr=3.91e-6, recon_loss=1.19e+4, task_loss=0.44] 


Mean Acc: 0.9613260860609731 F1 Score: 0.9898305630543821


Validating: 100%|██████████| 230/230 [01:01<00:00,  3.76it/s, F1=76.542, balanced_accuracy=66.205, lr=3.91e-6, recon_loss=7.81e+3, task_loss=1]    


Mean Acc: 0.48389602879661914 F1 Score: 0.7328159902381786
**************************************************
Epoch: 28
Epoch:  28 Total Training Task Loss:  300.04239320755005 Total Training Recon Loss: 6643755.553911388 Total Validation Task Loss:  237.32882869243622 Total Validation Recon Loss: 3252758.477423787
Epoch:  28 Total Validation Task Loss:  237.32882869243622 Total Validation Recon Loss: 3252758.477423787
Epoch:  28 Eval Acc 0.48389602879661914 F1 0.7328159902381786


Training: 100%|██████████| 656/656 [03:12<00:00,  3.41it/s, F1=98.904, balanced_accuracy=99.167, lr=1.06e-6, recon_loss=2.6e+4, task_loss=0.459]   


Mean Acc: 0.9592014179930164 F1 Score: 0.9895727506088201


Validating: 100%|██████████| 230/230 [01:00<00:00,  3.82it/s, F1=76.542, balanced_accuracy=66.205, lr=1.06e-6, recon_loss=7.81e+3, task_loss=1]    


Mean Acc: 0.4940050929502133 F1 Score: 0.739457335411311
**************************************************
Epoch: 29
Epoch:  29 Total Training Task Loss:  299.7169514596462 Total Training Recon Loss: 6646331.258494198 Total Validation Task Loss:  235.90111982822418 Total Validation Recon Loss: 3253284.916111946
Epoch:  29 Total Validation Task Loss:  235.90111982822418 Total Validation Recon Loss: 3253284.916111946
Epoch:  29 Eval Acc 0.4940050929502133 F1 0.739457335411311


Training: 100%|██████████| 656/656 [03:09<00:00,  3.46it/s, F1=99.066, balanced_accuracy=98.000, lr=1e-7, recon_loss=3.5e+3, task_loss=0.447]      


Mean Acc: 0.9609104668027132 F1 Score: 0.9897452164285557


Validating: 100%|██████████| 230/230 [01:02<00:00,  3.68it/s, F1=76.542, balanced_accuracy=66.205, lr=1e-7, recon_loss=7.81e+3, task_loss=1]    

Mean Acc: 0.4897586794408278 F1 Score: 0.7359182625909831
**************************************************
Epoch: 30
Epoch:  30 Total Training Task Loss:  299.47681352496147 Total Training Recon Loss: 6639491.313365102 Total Validation Task Loss:  236.00071996450424 Total Validation Recon Loss: 3253213.767627716
Epoch:  30 Total Validation Task Loss:  236.00071996450424 Total Validation Recon Loss: 3253213.767627716
Epoch:  30 Eval Acc 0.4897586794408278 F1 0.7359182625909831
